language: generic
sudo: required
services:
  -docker


before_install:
  -docker build -t jagasanD/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true jagasanD/docker-react-app npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  application: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-110656221591"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY